### ISSUE TITLE
Some web-sites are not opened on Mobile Data

### ISSUE THREAD

**Issue by PetrVladimirov** [celzero/rethink-app#1020]
On Mobile Data (LTE) some random web-sites (e.g. en.m.wikipedia.org) are not opened via a web-browser.

The same web-sites are opened when:
- Rethink is off OR
- Rethink is on and connections are made via Wi-Fi OR
- The web-browser is excluded from Rethink (Rethink's "Exclude" app mode).

In "Bypass DNS & Firewall" and "Bypass Universal" modes the web-browser cannot connect to these specific web-sites either.
 
The following didn't help:
- reloading Rethink DNS (Rethink GUI => DNS => Reload)
- reloading app list in Rethink 
- trying different Rethink DNS providers (system DNS, cloudflare DNS, 
- switching to Auto mode (IP6+IP4 instead of IP4)

Logs:
- show successful DNS resolution for these web-sites
- "Unnamed" apps (icons are correct)

Browser: Firefox
OS: Graphene OS (hardened pure Android) on v0.54 and v0.55

**Comment by ignoramous** [comment]
Do you have *Configure* -> *Network* -> *Enable network visibility* turned ON by any chance?

If not, what other *Network* related setting (in Rethink) have you changed?

**Comment by PetrVladimirov** [comment]
> Do you have _Configure_ -> _Network_ -> _Enable network visibility_ turned ON by any chance?
I've just tried - it doesn't hellp

> If not, what other _Network_ related setting (in Rethink) have you changed?
As far as I remember, I haven't changed anything. Everything is in "off" state. Please let me know if I should try anything else.

**Comment by PetrVladimirov** [comment]
> If not, what other _Network_ related setting (in Rethink) have you changed?
I've just tried multiple combinations with different Network related settings and none of them helped... Feel free to drop any specific one you want me to check.

**Comment by PetrVladimirov** [comment]
found another web-site example that is not opened on Mobile Data with Rethink on: _getpocket.com_

**Comment by ignoramous** [comment]
> Feel free to drop any specific one you want me to check.

Can you see if turning OFF *Advanced DNS Filtering* (from *Configure* -> *DNS*) fixes the issue?

Or, if changing *Choose IP version* to *Auto* (from *Configure* -> *Network*) fixes access over Mobile Data?

Or, if changing to *System DNS* works for you on Mobile Data?

Also, do you have trouble accessing other IPv4-only websites like `skysports.com` or `twitter.com`? I guess not.

**Comment by PetrVladimirov** [comment]
> Can you see if turning OFF _Advanced DNS Filtering_ (from _Configure_ -> _DNS_) fixes the issue?

It was already turned off.

> Or, if changing _Choose IP version_ to _Auto_ (from _Configure_ -> _Network_) fixes access over Mobile Data?

Tried it several times - doesn't help.

> Or, if changing to _System DNS_ works for you on Mobile Data?

Tried it several times - doesn't help.

> Also, do you have trouble accessing other IPv4-only websites like `skysports.com` or `twitter.com`? I guess not.

skysports.com - does work in all the modes listed above
twitter.com - doesn't work

**Comment by ignoramous** [comment]
Thanks. It seems like a very similar issue to #558

(apologies to bother you this much) 

> Tried it several times - doesn't help.

What "protos" does the bottomsheet that comes up when you tap the down arrow next to START/STOP button show in *Auto* mode?

Can you see if switching to *Private DNS* (say, `rec.max.rethinkdns.com` or `dns.adguard.com`) fixes connectivity to those websites?

You can also try if adding and using this Level66 DNS64 server `2001:67c:2960::64` (*Configure* -> *DNS* -> *Other* -> *DNS Proxy*) fixes Mobile Data (note that this DNS64 server won't work on IPv4 networks)?

**Comment by PetrVladimirov** [comment]
> (apologies to bother you this much)

no worries at all! You've been doing such a great job with this app, that I can only be grateful to you!

> What "protos" is shown in the bottomsheet that comes up when you tap the down arrow next to START/STOP button show in _Auto_ mode in wifi and mobile (you'll have to wait some 30s after switching before those get updated)?

**Wi-Fi**: switched from IP4 to Auto => waited for more than 60 sec => still showed IP4 => _Stop_ button => _Start_ button => Initially showed IP4 and IP6 => checked again in few seconds: shows only IP4

**Mobile data**: Turned off Wi-Fi (Network was in Auto mode) => showed IP4 only => _Stop_ button => _Start_ button => Initially showed IP4 and IP6 => checked again in few seconds: shows only IP4

> Can you see if switching to _Private DNS_ (say, `rec.max.rethinkdns.com` or `dns.adguard.com`) fixes connectivity to those websites?

I failed to add them manually via DoH => Plus button. It says "Invalid URL"
Used provided by the app: 
- on the DNScrypt tab:_Adguard_: doesn't help; 
- RDNS Max Plus: doesn't help

> You can also try if adding and using this Level66 DNS64 server `2001:67c:2960::64` (_Configure_ -> _DNS_ -> _Other_ -> _DNS Proxy_) fixes Mobile Data (note that this DNS64 server won't work on IPv4 networks)?

Can you please provide a port number? The app doesn't allow to add a DNS Proxy record without it.

**Comment by ignoramous** [comment]
> Can you please provide a port number? The app doesn't allow to add a DNS Proxy record without it.

Generic port number: `53`. In any case, this won't work since both mobile and wifi networks are IPv4-only from what you described.

> I failed to add them manually via DoH => Plus button. It says "Invalid URL"

Private DNS (DNS over TLS) in Android ([ref](https://archive.is/az65z)).

---

And when you're vising those websites that don't load, can you see what the corresponding *Network Log* entry for that website/domain shows once the connection has finished aka the connection isn't "Active" ([active connections are marked with a green-coloured dot](https://archive.is/CHzTo)). Tap on the *Network Log* entry and it should bring up a bottomsheet that should show the final connection status at the footer and other information (IP address, app name, domain name, protocol, time tc) in the header.

**Comment by PetrVladimirov** [comment]
> Private DNS (DNS over TLS) in Android ([ref](https://archive.is/az65z)).

With Rethink Off and Android Private DNS poiting to either `rec.max.rethinkdns.com` or `dns.adguard.com` the connection is succesful.

> And when you're vising those websites that don't load, can you see what the corresponding _Network Log_ entry for that website/domain shows once the connection has finished aka the connection isn't "Active" ([active connections are marked with a green-coloured dot](https://archive.is/CHzTo)). Tap on the _Network Log_ entry and it should bring up a bottomsheet that should show the final connection status at the footer and other information (IP address, app name, domain name, protocol, time tc) in the header.

**Comment by ignoramous** [comment]
Thanks. From the screenshot, it looks like the issue might be similar to #964 (fix for which will be part of the next release).

> With Rethink Off and Android Private DNS poiting to either rec.max.rethinkdns.com or dns.adguard.com the connection is succesful.

Leave Rethink in DNS+Firewall mode (make sure *Block when DNS is bypassed* is turned OFF) and see if the website works in mobile data?

> BTW - I haven't seen a green-coloured dot marked connections neither on LTE, nor on Wi-Fi even with an active download in progress. E.g. even during a download of a big file, the green dot wasn't shown.

Downloads are usually done through Android's built-in *Download Manager*. Make sure it isn't *excluded*.

Btw, does *Active* never show up *at all* even when connectivity is good (on Wifi)? We fixed a related bug #1000 for the next release, but not sure if what you're seeing is the same thing.

**Comment by PetrVladimirov** [comment]
> Thanks. From the screenshot, it looks like the issue might be similar to #964 (fix for which will be part of the next release; due 28 Aug).

Looking forward!

> > With Rethink Off and Android Private DNS poiting to either rec.max.rethinkdns.com or dns.adguard.com the connection is succesful.
> 
> With Private DNS and Rethink in DNS+Firewall mode (make sure _Block when DNS is bypassed_ is turned OFF), see if the website that fails starts working in mobile data? My guess is, it wouldn't...which would be a positive sign.

With Private DNS ON (rethink) and Rethink app ONN (DNS+Firewall mode) the website is still not accessible. I didn't find _Block when DNS is bypassed_ toggle anywhere in Rethink GUI though, so cannot comment whether it is OFF or ON...

> 
> > BTW - I haven't seen a green-coloured dot marked connections neither on LTE, nor on Wi-Fi even with an active download in progress. E.g. even during a download of a big file, the green dot wasn't shown.
> 
> Downloads are usually done through Android's built-in _Download Manager_. Make sure it isn't _excluded_.

Download Manager isn't excluded and it wasn't shown during the downloading activity...

> Btw, does _Active_ never show up _at all_ even when connectivity is good (on Wifi)? We fixed a related bug #1000 for the next release, but not sure if what you're seeing is the same thing.

Yes, I've never seen this green dot including on Wifi.

**Comment by ignoramous** [comment]
Can you please check if the problem persists on [`v055a`](https://www.reddit.com/r/rethinkdns/comments/166m2rd/v055a_a_glitch_in_the_matrix/)?

**Comment by PetrVladimirov** [comment]
Works like a charm! Green dots is also there now!

Thank you very much for the fix and this brilliant app!

**Comment by ignoramous** [comment]
Thanks for the confirmation and these detailed reports. It made the bug hunt easier.

Feel free to file more issues or requests (:
