### ISSUE TITLE
Add support to exclude domains

### ISSUE THREAD

**Issue by tlvince** [celzero/rethink-app#1153]
Along the same lines of the current allow LAN option ("Exclude LAN, loopback, multicast, link-local routes from Rethink's VPN tunnel"), could this be extended to exclude arbitrary domains?

One use case might be to allow `example.com` to bypass Rethink to be resolved locally.

NextDNS supports Excluded Domains "Domains that will bypass NextDNS and use the network-provided DNS." at least on [Apple profiles](https://apple.nextdns.io/):

![image](https://github.com/celzero/rethink-app/assets/323761/2fcc4124-e531-43a5-b23d-ad0c245bbe81)

**Comment by tlvince** [comment]
Precisely, but for DNS rather than Firewall.

**Comment by ignoramous** [comment]
> could this be extended to exclude arbitrary domains?

You mean, sending these domains to "System DNS"? In v055b (not yet released) we detect `.local` (#1005) / `.lan` / `.internal` etc top-level domains and send it to  *System DNS*, by default. Would that suffice?

**Comment by ignoramous** [comment]
>  For me at least, I have to turn off private dns to use Rethink. Might not be the case for others.

To use DNS-based rules with the Rethink app, you'd *have* to turn off *Private DNS*.

>  So I just assumed it being resolved locally, I guess its not the case?

All DNS queries are forwarded to user-selected upstream DNS resolver. The Rethink app isn't a recursive resolver (doesn't do ANY resolution on its own *except* for grounding queries of blocked domains).

> Is this how it supposed to work?

Yes, if *Private DNS* is enabled (#25), then it takes precedence over the DNS endpoint set by Rethink.

> Maybe the developer/maintainer would know better.

You'd think... but ;)

**Comment by Ariessanea1** [comment]
When do get paid for this

**Comment by 1MichaS1** [comment]
Please also allow the user to specify that "**non-domains**" (is this a word?) **get resolved by "System DNS"**. With non-domains I mean **hostnames without any TLD**. Typically in the local home network one has device hostnames like "my-socket" or "serverAbc".

I do not want to change them all to "my-socket.local" etc., this is clumsy, and I would have to re-configure all my apps that call these home devices by their today's name. And I'd have to do much more typing ("... .local") whenever addressing them from my home browser or from the console or whatever.

Concrete use case is that I make a VPN WireGuard tunnel from my phone to my home network, and my phone apps that send http requests to home devices like "my-socket" now fail because these devices' hostnames do not get resolved by Rethink DNS. So I currently have to set DNS in RethinkDns app globally to "System DNS" for this to work and lose the benefits of the Rethink DNS lookups.

**Comment by RodoMa92** [comment]
> > could this be extended to exclude arbitrary domains?
> 
> You mean, sending these domains to "System DNS"? In v055b (not yet released) we detect `.local` (#1005) / `.lan` / `.internal` etc top-level domains and send it to _System DNS_, by default. Would that suffice?

I can't get it to work with .lan domains, they always seems to fail resolution even with the private ip option enabled. Another possible question is what if I want to use the DNS provided by my wireguard Proxy connection to resolve internal services on the intranet? Is that currently possible? This is one last piece to be able to access my local services plus having a robust DNS protection on my smartphone :)

**Comment by ignoramous** [comment]
> Yep, this shows rethink dns responding to it and failing since it's not a valid TLD.
 
Dang (a regression from having fixed #1297)
- #1466 

> I'll watch these then in the hope that they will fix my issue once merged.

Fixing this requires fundamental changes to the network engine... so, don't hold your breath...

> Thanks a lot for your work!

:+1:

**Comment by RodoMa92** [comment]
>  > Yep, this shows rethink dns responding to it and failing since it's not a valid TLD.
>  
> Dang (a regression from having fixed #1297)
> - #1466 
> 
> > I'll watch these then in the hope that they will fix my issue once merged.
> 
> Fixing this requires fundamental changes to the network engine... so, don't hold your breath...
> 
> > Thanks a lot for your work!
> 
> :+1: 

Oh, lol, missed a dot in the domain name. Happens to the best of us. Thanks for the quick fix BTW!

**Comment by RodoMa92** [comment]
Sadly, as of today, it still doesn't seem to work. Any .lan domains still get sent to upstream (*.rethinkdns.com) instead of my local resolver. Trying with .local still seems to work alright, I can see a multicast dns request to a private subnet. I'll take a look at the code, but I can't promise much though.

**Comment by yoshimo** [comment]
Is https://www.rfc-editor.org/rfc/rfc9704.html covering this use case?

**Comment by txtsd** [comment]
On my local network, I use a custom TLD in order for all my services to be subdomains of `khazad.dum`.

I would like to be able to configure rethink to let the system DNS answer queries for this domain or TLD.

Is this possible?

**Comment by NealPierceGH** [comment]
I'll explain my own use case and maybe someday there will be some options/features in Rethink to make it work seamlessly.

I have a home lab and I host all of my services and I rely a lot on DNS in split mode, a side for the LAN and a side for the outside world.

My main phone uses 5G most of the time with Rethink doing all the filtering and the DNS set to Quad9 and RethinkDNS (depending on the mood 😄 ). When I want to use the WiFi on the phone, I have to 
* Disable 4G/5G data as a precaution as I don't have a way to see if DNS queries leak through that network
* Turn on WiFI
* Change DNS in Rethink to switch from Quad9/RethinkDNS to SystemDNS so I can resolve my split DNS domain (regular domain, not .lan/.local or similar) to internal IP addreses
* Hit the refresh button on DNS force Rethink to use the SystemDNS (or at least, clear the cache and start fresh)

Now I can use any service I host on my internal network seamlessly without any issue. I have then to revert all that when turning off WiFi and getting back to 4G/5G only.

I may be in a niche use case so don't worry to much but what I really dream of is some kind of Network Profiles concept where I could specify some rules, something like this
- Profile : Mobile network
   DNS rules
      1. Domain: *.example.com -> shadydns.somewhere.tld  - or -  1.2.3.4 IP address
      2. Domain: * -> Quad9/RethinkDNS
 - Profile : Wifi Home
   SSID: MyFriendlyHomeWiFi
   DNS rules
       1. Domain: *.myowndomain.com -> dns.myowndomain.com - or - 10.10.10.53 IP address (internal)
       2. Domain: * -> dns.myowndomain.com or any other (makes little sense but why not)
 - Profile : WiFi anywhere
    SSID: *
    DNS rules
        2. Domain: * -> Quad9/RethinkDNS
 
That's merely an idea out of my head, I can leave without any of this and do things manually as I already do. There are tons of problems and corner cases with that kind of configuration, not even speaking about the complexity of implementing this.
