### ISSUE TITLE
Bug: Block any app not in use - Blocks itself

### ISSUE THREAD

**Issue by aviv926** [celzero/rethink-app#2483]
When the Block any app not in use feature is enabled (Configue - Firewall - Block any app not in use) then in version v0.5.5u it causes a problem where after a few minutes there is no access to the internet at all.

I assume the problem is because in the new version the Rethink application appears in the application list under "Apps" (which as I remember was not in the latest stable version v0.5.5n)
Therefore this causes the Rethink application to activate the Block any app not in use rule on itself.

In the latest stable version v0.5.5n the problem does not appear, but I am in version v0.5.5u because it addresses the IP address leak issue (when WireGuard is active) in certain scenarios that was only addressed in v0.5.5n.

Recovery instructions:
Use version v0.5.5u -> Enable the Block any app not in use setting -> Clear all recently opened apps -> Wait a few minutes -> No internet access.

**Comment by L-3-m-o-n** [comment]
I spotted this too , In my case it blocked Android's DNS app (used for private dns in android) leading to no internet connection immediately .

**Comment by ignoramous** [comment]
> Therefore this causes the Rethink application to activate the Block any app not in use rule on itself

This isn't yet implemented, but will be in `v055v`: 
- #2422 

See if you spot any blocked entries in *Configure -> Logs -> DNS* or *Configure -> Logs -> Network*. Blocked entries are usually marked with red-coloured left-hand side border. Tapping on these should bring up a *bottomsheet* which should show more information about the connection entry, including why it may have been blocked.

**Comment by L-3-m-o-n** [comment]
@ignoramous 

![Screenshot_2026-01-02-06-41-19-56_c8cbde12d3521911922be4eee6a05664.jpg](https://github.com/user-attachments/assets/620cf854-ab37-45ec-bb10-b4682cc6f7c0)

This was also being blocked by the same feature , It is required for Android's Private DNS to work otherwise No Internet Connection and while using Private DNS - Ultimately that rethink feature is pretty much useless (No internet connection) and it likely isn't a package since it mentions No Package below app name , Will this also be fixed in next update ?

**Comment by ignoramous** [comment]
If the feature is blocking `DNS` (a system component), user has to explicitly "Bypass Universal" or "Bypass DNS and Firewall" it. We can do so by default but some might not be expecting that.

There's a lot of other subtle such issues with "Block any app not in use", and so, it remains a power user feature.

**Comment by aviv926** [comment]
> > Therefore this causes the Rethink application to activate the Block any app not in use rule on itself
> 
> This isn't yet implemented, but will be in `v055v`:
> 
>     * [Firewall Rethink using Rethink #2422](https://github.com/celzero/rethink-app/issues/2422)
> 
> 
> See if you spot any blocked entries in _Configure -> Logs -> DNS_ or _Configure -> Logs -> Network_. Blocked entries are usually marked with red-coloured left-hand side border. Tapping on these should bring up a _bottomsheet_ which should show more information about the connection entry, including why it may have been blocked.

Actually it's even weirder
When I go to the logs and the Block any app not in use option is active then it stops showing me any apps trying to access the network and only shows apps that are configured with Bypass DNS and Firewall so there is definitely a weird bug here.
Can you test this behavior on your end?

**Comment by ignoramous** [comment]
> it stops showing me any apps trying to access the network and only shows apps that are configured with Bypass DNS and Firewall so there is definitely a weird bug here

If you're on Android 12+ and have *Configure -> DNS -> Split DNS* turned ON, the reason you may not see anything in *Configure -> Logs -> Network* is because the DNS requests were themselves blocked (which would appear in *Configure -> Logs -> DNS*).

**Comment by aviv926** [comment]
> > it stops showing me any apps trying to access the network and only shows apps that are configured with Bypass DNS and Firewall so there is definitely a weird bug here
> 
> If you're on Android 12+ and have *Configure -> DNS -> Split DNS* turned ON, the reason you may not see anything in *Configure -> Logs -> Network* is because the DNS requests were themselves blocked (which would appear in *Configure -> Logs -> DNS*).


Split DNS set to off
Logs -> Network - Still does not show blocked traffic when the blocking option is enabled.

Logs: 

1767601514831,E RethinkUI: err submitting data: Job was cancelled

1767601518030,E RethinkUI: err submitting data: Job was cancelled 


My setup:
DNS DoH
VPN always on, advanced mode.
block list. 
Accessibility settings are on (I tried disabling access and restoring - no change)
No battery limitation for background activity

**Comment by aviv926** [comment]
A search on the channel's Telegram shows more people with a similar problem. The search terms are: "block any app not in use"

**Comment by ignoramous** [comment]
We will test for the issue reported here along with #2551

**Comment by ignoramous** [comment]
[`v055x`](https://github.com/celzero/rethink-app/releases/tag/v0.5.5x) should have fixed the issue reported here (though, it has other bugs), per our testing and as reported by a few other users. Do test and let me know if that isn't the case, I'll reopen this bug.
 
- #2741 
- #2606
